name: 'number_ladder_game'
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  bootstrap: 3.3.7
  dragula:
    git: https://github.com/sircco/dragula.dart.git

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
- bootstrap:
    url: //maxcdn.bootstrapcdn.com/bootstrap/{{version}}
    version: 3.3.7